"""project taste

Revision ID: 0b6023eae116
Revises: 2d1d3e3192e7
Create Date: 2026-09-12 03:54:30.651285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b6023eae116'
down_revision: Union[str, Sequence[str], None] = '2d1d3e3192e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('taste', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'taste')
    # ### end Alembic commands ###
