"""project auto_render

Revision ID: 237d0e1570aa
Revises: 0b6023eae116
Create Date: 2026-09-12 04:07:06.170510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237d0e1570aa'
down_revision: Union[str, Sequence[str], None] = '0b6023eae116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('auto_render', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('projects', 'auto_render', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'auto_render')
    # ### end Alembic commands ###
