"""project retention_warned_at

Revision ID: 2d1d3e3192e7
Revises: 6de74cecf724
Create Date: 2026-09-04 07:54:48.696942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d1d3e3192e7'
down_revision: Union[str, Sequence[str], None] = '6de74cecf724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('retention_warned_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'retention_warned_at')
    # ### end Alembic commands ###
